# Generated by Django 6.0.5 on 2026-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('muallifi', models.CharField(max_length=100)),
                ('janri', models.CharField(max_length=50)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tavsif', models.TextField()),
            ],
        ),
    ]
