# Generated by Django 6.0.5 on 2026-05-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.PositiveIntegerField(default=1)),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
                ('holati', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tayyorlanmoqda', 'Tayyorlanmoqda'), ('Yakunlandi', 'Yakunlandi')], default='Kutilmoqda', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tavsifi', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tolov_vaqti', models.DateTimeField(auto_now_add=True)),
                ('tolov_turi', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='taom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taom'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='buyurtma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.buyurtma'),
        ),
    ]
