# Generated by Django 6.0.5 on 2026-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buyurtma_taom_tolov_delete_kitob_buyurtma_taom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taom',
            name='chegirma_foizi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taom',
            name='chegirma_kuni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
